# Server Configuration
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subhir625@gmail.com
spring.mail.password=usnkfvqqffbothnh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false

# App Emails
app.ceo.email=ceo@nmit.ac.in
app.ceo.name=CEO
app.hod.email=hod@nmit.ac.in
app.hod.name=HOD