# Server Configuration
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/dutyexchange}

# Email Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=aa13b1001@smtp-brevo.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App Emails (for testing)
app.ceo.email=kumarbhuvan032@gmail.com
app.ceo.name=CEO

app.hod.email=Subhir625@gmail.com
app.hod.name=HOD